### register
POST  http://localhost:4500/users/register
Content-Type: application/json

{
   
    "username": "jesso",
    "email":"so@thejitu.com",
    "password":"12345678",
    "full_name": "jessyopeno",
    "profile_picture": "http://localhost:4500/users/login"
}

# { username, email, password, full_name, profile_picture } 

### login
POST  http://localhost:4500/users/login
Content-Type: application/json

{
    "email":"milla.jesso@thejitu.com",
    "password":"12345678"
}

### verify otp
POST  http://localhost:4500/users/verifyotp
Content-Type: application/json

{
    "otp":"644159",
    "userEmail":"jessyopeno2000@gmail.com"

}

### reset password
POST  http://localhost:4500/reset/resetPassword
Content-Type: application/json

{
    "email": "jessyopeno2000@gmail.com"   
}

### setting new password
POST  http://localhost:4500/reset/updatePassword
Content-Type: application/json

{
    "resetToken": "20169157-57f7-44b2-acbd-791c35835856",
    "newPassword": "milla789"
    
}








###  get a single user
GET http://localhost:4500/users/singleusers/36d7e3cd-49f4-4cb6-9171-a3f926fc7546
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ



###edit user details
PUT http://localhost:4500/users/edit/36d7e3cd-49f4-4cb6-9171-a3f926fc7546
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ
 
{
  "username": "millajesso",
  "email": "dennissplit203@gmail.com",       
  "full_name": "BethWaweru",    
  "profile_picture": "09c4447b-5d7a-4b3a-89d2-97f22886b405"     

}

###soft delete user
DELETE  http://localhost:4500/users/softdelete/36d7e3cd-49f4-4cb6-9171-a3f926fc7546
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ




### GET ALL user on linkup
GET http://localhost:4500/users/getallusers
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ











### GET ONE Post
GET http://localhost:4500/posts/94b1ff10-281c-4c03-905b-fbf4337cb99f
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5nYXRpYTExMTExMTE0MSIsImVtYWlsIjoiamVzc29AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkTUI4MGVkaUN6LkNYaG9CUUJJT2Y0dXlVdTdhVk9Cck9yQS51VnFLb21vZjY2bzF5bnZ6YlciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yN1QxNTo1MToxOS44ODNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkzMTU0MDUzLCJleHAiOjE2OTMxOTAwNTN9.OrMdrIb8GIklUKSjv7XkO1-XyWDczKhhAUqgqqnILEI


### UPDATING a post
PUT http://localhost:4500/posts/edityourpost
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ


{   
    "post_id": "94b1ff10-281c-4c03-905b-fbf4337cb99f",
    "user_id": "36d7e3cd-49f4-4cb6-9171-a3f926fc7546",
    "newContent": "BIG JESSY UPDATED",
    "newImageUrl": "https://example.com/image.jpg"
}

###delete post
DELETE http://localhost:4500/posts/softdeleteyourpost
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{   
    "post_id": "94b1ff10-281c-4c03-905b-fbf4337cb99f",
    "user_id": "36d7e3cd-49f4-4cb6-9171-a3f926fc7546"
    
}

###get post by user id
GET http://localhost:4500/posts/getpostsbyuserid/36d7e3cd-49f4-4cb6-9171-a3f926fc7546
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ


### create a comment
POST  http://localhost:4500/comments/createcomment
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "postId": "94b1ff10-281c-4c03-905b-fbf4337cb99f",
    "userId": "01436d12-3006-4c7d-85ad-aa12f466e932",
    "content": "comment to a subcomment",
    "parentCommentId": "61c8e0ab-df17-4557-be91-1f0600026caf"
    
}

# postId, userId, content, parentCommentId

### edit a comment
PUT  http://localhost:4500/comments/editcomment
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "comment_id": "61c8e0ab-df17-4557-be91-1f0600026caf",
    "user_id": "01436d12-3006-4c7d-85ad-aa12f466e932",
    "newContent": "updated comment"
    
}

# comment_id, user_id, newContent 


### getcomments for a post for or a comment as subcomments
GET  http://localhost:4500/comments/getcomments
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "postId": "94b1ff10-281c-4c03-905b-fbf4337cb99f"  
}

# postId, commentId
# "commentId": "61c8e0ab-df17-4557-be91-1f0600026caf"  for subcomments


### soft delete a comment
DELETE http://localhost:4500/comments/softDeleteComment
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "comment_id": "374de6a0-d8e8-4d69-86a4-6548e35985b7",
    "user_id": "01436d12-3006-4c7d-85ad-aa12f466e932"  
}

# comment_id, user_id




# FOLLOW AND FOLLOWING CONTROLLERS

### follow a user 
POST http://localhost:4500/friends/follow
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "follower_id": "aa635f57-a520-44e4-a6bd-4751b61c2473",
    "following_id": "0799d3dd-a2ea-4c7d-b44c-2965dd6a12b4"  
}

# follower_id refers to the user who is following another user.
# following_id refers to the user who is being followed by the follower_id.
# 1154ab55-36e5-4a97-b428-7841aff98c3d
# 7c921322-aee9-49dc-8fea-314f080bb0a9
# aa635f57-a520-44e4-a6bd-4751b61c2473



### unfollow a user 
POST http://localhost:4500/friends/unfollow
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "follower_id": "01436d12-3006-4c7d-85ad-aa12f466e932",
    "following_id": "0799d3dd-a2ea-4c7d-b44c-2965dd6a12b4"  
}

# follower_id refers to the user who is following another user.
# following_id refers to the user who is being followed by the follower_id.

### get a users followers/ the people who are following a this user
GET http://localhost:4500/friends/followers/0799d3dd-a2ea-4c7d-b44c-2965dd6a12b4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ


### get the people a user is following
GET http://localhost:4500/friends/following/0799d3dd-a2ea-4c7d-b44c-2965dd6a12b4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ



# LIKE AND UNLIKE POST OR COMMENT END POINT

### like/ unlike a post
POST http://localhost:4500/likes/like-unlike-post
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{

    "user_id": "7c921322-aee9-49dc-8fea-314f080bb0a9",
    "post_id": "94b1ff10-281c-4c03-905b-fbf4337cb99f"  
}



# user_id , post_id

### like/ unlike a comment
POST http://localhost:4500/likes/like-unlike-comment
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHAiOiI5NTY0NDEiLCJvdHBFeHBpcnkiOiIyMDIzLTA5LTEwVDE1OjMzOjA2LjI3N1oiLCJpYXQiOjE2OTQzNTk0MTIsImV4cCI6MTY5NDcxOTQxMn0.IGKstDfUBzVJIm07ksu8KLGXIegVEvHFWfAbdGn6dAQ

{
    "user_id": "1154ab55-36e5-4a97-b428-7841aff98c3d",
    "comment_id": "61c8e0ab-df17-4557-be91-1f0600026caf"  
}

# user_id , comment_id


# users ids

# 1154ab55-36e5-4a97-b428-7841aff98c3d
# 7c921322-aee9-49dc-8fea-314f080bb0a9
# aa635f57-a520-44e4-a6bd-4751b61c2473

### GET ONE Post
GET http://localhost:4500/posts/94b1ff10-281c-4c03-905b-fbf4337cb99f
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5nYXRpYTExMTExMTE0MSIsImVtYWlsIjoiamVzc29AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkTUI4MGVkaUN6LkNYaG9CUUJJT2Y0dXlVdTdhVk9Cck9yQS51VnFLb21vZjY2bzF5bnZ6YlciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yN1QxNTo1MToxOS44ODNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkzMTU0MDUzLCJleHAiOjE2OTMxOTAwNTN9.OrMdrIb8GIklUKSjv7XkO1-XyWDczKhhAUqgqqnILEI



